library(clusterGeneration)
library(deSolve)
library(MASS)
library(ggplot2)
library(dplyr)
library(tidyr)



##########################################

# simulation with random perturbations every n timesteps. I compute the covariance in species' biomass responses

##########################################

# Function to simulate quantitative interaction network
sim_quantitative_network <- function(Net_type, S, C, aij_params) {
  A <- matrix(0, S, S)
  n_pairs <- S * (S - 1) / 2
  B <- runif(n_pairs) <= C
  if (Net_type == "predator-prey") { 
    aij <- -abs(rnorm(n_pairs, aij_params[1], aij_params[2]))
    A[upper.tri(A)] <- B * aij
    A <- t(A)
    aij <- abs(rnorm(n_pairs, aij_params[1], aij_params[2]))
    A[upper.tri(A)] <- B * aij
  } 
  diag(A) <- -runif(S, min = 0, max = 1)
  while(max(Re(eigen(A)$values)) > 0){
    diag(A) <- -runif(S, min = 0, max = 1)
  }
  return(A)
}

# Function to simulate dynamics with discrete perturbations
simulate_with_discrete_perturbations <- function(S, timesteps, cov_matrix, perturb_interval = 20, perturb_scale = 1) {
  # Initialize species parameters and biomasses
  A <- sim_quantitative_network("predator-prey", S = S, C = 0.2, aij_params = c(0, 0.5))
  init_biomass <- runif(S, min = 1, max = 10)
  r <- -A %*% init_biomass  # Initial r values based on biomass
  
  # Accumulating growth rates for each species (initialized as r)
  r_new <- r
  biomass <- init_biomass
  
  # Create a data frame to store results, ensuring that column names match
  results <- data.frame(time = 1, t(biomass))  # Transpose biomass vector to match the shape
  colnames(results) <- c("time", paste0("species_", 1:S))
  
  # Iterate over time in discrete blocks, applying perturbations at specified intervals
  for (t in seq(perturb_interval, timesteps, by = perturb_interval)) {
    # Apply perturbation at each interval
    delta_r <- MASS::mvrnorm(n = 1, mu = rep(0, S), Sigma = cov_matrix) * perturb_scale
    r_new <- r_new + delta_r  # Update growth rates with perturbation
    
    # Define the ODE model using the new r_new
    fw.model_block <- function(t, B, params) {
      with(as.list(c(B, params)), {
        B[B < 10^-8] <- 0  # Avoid negative biomass
        dBdt <- (params$r_new + params$A %*% B) * B  # Use updated r_new
        list(dBdt)
      })
    }
    
    # Simulate the system for the next perturb_interval timesteps
    out <- deSolve::ode(
      y = biomass, 
      times = seq(t - perturb_interval + 1, t), 
      func = fw.model_block, 
      parms = list(A = A, r_new = r_new),
      method = "ode45"  # Use a solver for non-stiff systems
    )
    
    # Update biomass to the last step of the block and store results
    biomass <- as.numeric(out[nrow(out), -1])  # Extract the last row (new biomass)
    time_block_results <- data.frame(time = t, t(biomass))  # Transpose and create a data frame
    colnames(time_block_results) <- colnames(results)  # Ensure the column names match
    
    results <- rbind(results, time_block_results)  # Append the new results
    
    # print(paste("Applied perturbation at time", t, ": delta_r =", paste(delta_r, collapse = ", ")))
  }
  
  return(results)
}

# Function to generate covariance matrix based on emergent dynamics
generate_cov_matrix <- function(S) {
  cor_matrix <- clusterGeneration::rcorrmatrix(d = S, alphad = 1)  # Generate random correlation matrix
  sd_X <- rep(1, S)  # Assuming standard deviation of 1 for simplicity
  cov_matrix <- diag(sd_X) %*% cor_matrix %*% diag(sd_X)
  return(cov_matrix)
}

# Number of simulations
nsim <- 200
S <- 20  # Number of species
timesteps <- 1000

# Initialize an empty list to store the results for each simulation
all_sim_results <- list()
cov_values <- data.frame()  # Initialize an empty dataframe to store covariance values
variance_covariance <- data.frame()  # DataFrame to store variance in covariance
sd_covariance <- data.frame()
mean_covariance <- data.frame()  # DataFrame to store mean of covariance values

# Run simulations
for (sim in 1:nsim) {
  
  print(paste("sim", sim, "of", nsim))
  
  # Generate covariance matrix based on emergent dynamics
  cov_matrix <- generate_cov_matrix(S)
  
  # Run the simulation with the generated covariance matrix
  result <- simulate_with_discrete_perturbations(S = S, timesteps = timesteps, cov_matrix = cov_matrix, perturb_scale = 1.2)
  
  # Add sim_id to the result for identification
  result$sim_id <- sim
  
  # Store the result in the list
  all_sim_results[[sim]] <- result
  
  # Calculate biomass change between consecutive timesteps for covariance calculation
  biomass_diff <- result %>%
    dplyr::select(-time, -sim_id) %>%  # Select all columns except time and sim_id
    mutate(across(everything(), ~ . - lag(.))) %>%  # Calculate the difference between consecutive timesteps
    na.omit()  # Remove rows with NA values generated by lag()
  
  # Compute covariance matrix of the biomass changes
  biomass_cov_matrix <- cov(biomass_diff)
  
  # Extract and store the upper triangle of the covariance matrix (without diagonal)
  cov_vals <- biomass_cov_matrix[upper.tri(biomass_cov_matrix)]
  cov_values <- rbind(cov_values, data.frame(sim_id = sim, covariance = cov_vals))
  
  # Store variance and mean of covariance values for this simulation
  variance_covariance <- rbind(variance_covariance, data.frame(sim_id = sim, var_cov = var(cov_vals)))
  sd_covariance <- rbind(sd_covariance, data.frame(sim_id = sim, sd_cov = sd(cov_vals)))
  mean_covariance <- rbind(mean_covariance, data.frame(sim_id = sim, mean_cov = mean(cov_vals)))
}

# Combine results for all simulations into one data frame
combined_results <- do.call(rbind, all_sim_results)

# Convert results to long format for easier analysis
combined_long <- combined_results %>%
  pivot_longer(cols = starts_with("species_"), names_to = "species", values_to = "biomass")

# Calculate biomass changes for each species over time, for each simulation
biomass_change_stats <- combined_long %>%
  group_by(species, sim_id) %>%
  arrange(time) %>%
  mutate(biomass_change = biomass - lag(biomass)) %>%  # Calculate biomass change between timesteps
  filter(!is.na(biomass_change)) %>%  # Remove NA values created by lag
  summarise(mean_change = mean(biomass_change, na.rm = TRUE),
            variance_change = var(biomass_change, na.rm = TRUE)) %>%
  ungroup()

# Combine biomass change variance with covariance variance
biomass_var_cov <- biomass_change_stats %>%
  group_by(sim_id) %>%
  summarise(variance_abundance_change = mean(variance_change, na.rm = TRUE)) %>%
  inner_join(variance_covariance, by = "sim_id") %>%
  inner_join(sd_covariance, by = "sim_id") |> 
  inner_join(mean_covariance, by = "sim_id")

# Plot 1: Biomass dynamics for one simulation (use the first simulation)

biomass_one_sim <- combined_long %>%
  filter(sim_id == 14)

p1 <- ggplot(biomass_one_sim, aes(x = time, y = biomass, color = species)) +
  geom_line() +
  labs(title = "Biomass Dynamics for One Simulation", x = "Time", y = "Biomass") +
  theme_minimal()

# Plot 1.2: Biomass dynamics for several simulations

# Select 8 simulations to plot
selected_sim_ids <- c(1, 2, 3, 4, 5, 6, 7, 8)  # Modify if you want different simulations

# Filter the data for the selected simulations
biomass_multiple_sims <- combined_long %>%
  filter(sim_id %in% selected_sim_ids)

# Create the combined plot
p1.2 <- ggplot(biomass_multiple_sims, aes(x = time, y = biomass, color = species)) +
  geom_line() +
  facet_wrap(~ sim_id, ncol = 4) +  # Facet by simulation ID, arranged in 2 rows and 4 columns
  labs(title = "Biomass Dynamics Across 8 Simulations", x = "Time", y = "Biomass") +
  theme_minimal() +
  theme(legend.position = "none")  # Remove the legend for species to avoid clutter


# Plot 2: Boxplot of mean change in biomass for all simulations
p2 <- ggplot(biomass_change_stats, aes(x = as.factor(sim_id), y = mean_change)) +
  geom_boxplot(fill = "skyblue") +
  labs(title = "Mean Change in Biomass Across Simulations", x = "Simulation", y = "Mean Change in Biomass") +
  theme_minimal()

# Plot 3: Boxplot of variance in biomass change for all simulations
p3 <- ggplot(biomass_change_stats, aes(x = as.factor(sim_id), y = variance_change)) +
  geom_boxplot(fill = "orange") +
  labs(title = "Variance in Biomass Change Across Simulations", x = "Simulation", y = "Variance in Biomass Change") +
  theme_minimal()

# Plot 4: Distribution of covariance values across simulations
p4 <- ggplot(cov_values, aes(x = covariance)) +
  geom_histogram(bins = 30, fill = "red", alpha = 0.7) +
  facet_wrap(~ sim_id, scales = "free") +
  theme_minimal() +
  ggtitle("Distribution of Covariance Values Across Simulations") +
  labs(x = "Covariance", y = "Frequency")

# Plot 5: Mean covariance vs. variance in abundance change
p5 <- ggplot(biomass_var_cov, aes(x = mean_cov, y = variance_abundance_change)) +
  geom_point(size = 3, color = "blue") +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  labs(title = "Mean Covariance vs Variance in Abundance Change", x = "Mean Covariance", y = "Variance in Abundance Change") +
  theme_minimal()

# Plot 6: Variance of covariance vs. variance in abundance change
p6 <- ggplot(biomass_var_cov, aes(x = var_cov, y = variance_abundance_change)) +
  geom_point(size = 3, color = "green") +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  labs(title = "Variance of Covariance vs Variance in Abundance Change", x = "Variance of Covariance", y = "Variance in Abundance Change") +
  theme_minimal()

# Plot 7: sd of covariance vs. variance in abundance change
p7 <- ggplot(biomass_var_cov, aes(x = sd_cov, y = variance_abundance_change)) +
  geom_point(size = 3, color = "green") +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  labs(title = "SD of Covariance vs Variance in Abundance Change", x = "Variance of Covariance", y = "Variance in Abundance Change") +
  theme_minimal()

# Display the plots
print(p1)  # Biomass dynamics for one simulation
print(p1.2)  # Biomass dynamics for several simulations
print(p2)  # Boxplot for mean change across all simulations
print(p3)  # Boxplot for variance in biomass change across all simulations
print(p4)  # Distribution of covariance values across simulations
print(p5)  # Mean covariance vs variance in abundance change
print(p6)  # Variance of covariance vs variance in abundance change
print(p7)  # SD of covariance vs variance in abundance change

#######################################


# Choose 3 simulations to plot
chosen_sim_ids <- c(1, 2, 3)

# Filter the data for the selected simulations
biomass_chosen_sims <- combined_long %>%
  filter(sim_id %in% chosen_sim_ids)

cov_chosen_sims <- cov_values %>%
  filter(sim_id %in% chosen_sim_ids)

# Plot 1: Distribution of covariance values for the chosen simulations
p_cov <- ggplot(cov_chosen_sims, aes(x = covariance)) +
  geom_histogram(bins = 30, fill = "red", alpha = 0.7) +
  facet_wrap(~ sim_id, scales = "free_x") +
  theme_minimal() +
  ggtitle("Distribution of Covariance Values for Chosen Simulations") +
  labs(x = "Covariance", y = "Frequency")

# Plot 2: Biomass dynamics for the chosen simulations (horizontally arranged and no legend)
p_biomass <- ggplot(biomass_chosen_sims, aes(x = time, y = biomass, color = species)) +
  geom_line() +
  facet_wrap(~ sim_id, ncol = 3) +  # Arrange horizontally with 3 columns
  labs(title = "Biomass Dynamics for Chosen Simulations", x = "Time", y = "Biomass") +
  theme_minimal() +
  theme(legend.position = "none")  # Remove the legend for biomass species

# Combine the two plots into a single figure with grid arrangement
combined_plot <- grid.arrange(p_cov, p_biomass, ncol = 1, heights = c(1, 1.5))

# Display the combined plot
print(combined_plot)
